{% set version = "0.1.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-smdocker
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/smdocker_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/smdocker/smdocker_{{ version }}.tar.gz
  sha256: 6db1c3be00645e5c23aa4782f0ad4f11e974e8d34fcb9678a862cc1c036a538e

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-jsonlite
    - r-paws.compute
    - r-paws.developer.tools
    - r-paws.machine.learning
    - r-paws.management
    - r-paws.security.identity
    - r-paws.storage
    - r-uuid
    - r-zip
  run:
    - r-base
    - r-jsonlite
    - r-paws.compute
    - r-paws.developer.tools
    - r-paws.machine.learning
    - r-paws.management
    - r-paws.security.identity
    - r-paws.storage
    - r-uuid
    - r-zip

test:
  commands:
    - $R -e "library('smdocker')"           # [not win]
    - "\"%R%\" -e \"library('smdocker')\""  # [win]

about:
  home: https://github.com/DyfanJones/sm-docker
  license: MIT
  summary: Allows users to easily build custom 'docker images' <https://docs.docker.com/> from 'Amazon Web Service Sagemaker' <https://aws.amazon.com/sagemaker/> using 'Amazon Web Service CodeBuild' <https://aws.amazon.com/codebuild/>.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: smdocker
# Title: Build 'Docker Images' in 'Amazon SageMaker Studio' using 'Amazon Web Service CodeBuild'
# Version: 0.1.3
# Authors@R: c(person("Dyfan", "Jones", email="dyfan.r.jones@gmail.com", role= c("aut", "cre")))
# Description: Allows users to easily build custom 'docker images' <https://docs.docker.com/> from 'Amazon Web Service Sagemaker' <https://aws.amazon.com/sagemaker/> using 'Amazon Web Service CodeBuild' <https://aws.amazon.com/codebuild/>.
# License: MIT + file LICENSE
# URL: https://github.com/DyfanJones/sm-docker
# BugReports: https://github.com/DyfanJones/sm-docker/issues
# Encoding: UTF-8
# Imports: jsonlite, paws.compute, paws.developer.tools, paws.machine.learning, paws.management, paws.storage, paws.security.identity, zip, stats, utils, uuid
# Suggests: covr, crayon, mockery, testthat (>= 3.0.0)
# RoxygenNote: 7.2.3
# Collate: 'utils.R' 'logs.R' 'code_build.R' 'builder.R' 'config.R' 'logging.R' 'sm_role.R' 'main.R' 'zzz.R'
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2023-05-15 17:13:47 UTC; dyfanjones
# Author: Dyfan Jones [aut, cre]
# Maintainer: Dyfan Jones <dyfan.r.jones@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-05-15 17:30:02 UTC
